language: cpp

git:
  depth: 1

addons: &gcc7
  apt:
    packages:
      - g++-7
    sources:
      - ubuntu-toolchain-r-test

addons: &clang6
  apt:
    packages:
      - clang-6.0
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-6.0

matrix:
  include:
    - env: CXX="g++-7" CC="gcc-7" CPP_CHECK=1 USE_GLFW=1
      os: linux
      dist: bionic
      addons: &gcc7

    - env: CXX="clang++-6.0" CC="clang-6.0"
      os: linux
      dist: bionic
      addons: &clang6

before_install:
  - sudo apt-get -y install libopencv-dev libglfw3-dev libgles2-mesa-dev cppcheck

before_script:
  - $CXX --version
  - cmake --version
  - if [[ ${USE_GLFW} ]]; then export CMAKE_FLAGS="-DUSE_GLFW=1"; fi

script:
    - mkdir -p build && cd build
    - cmake .. ${CMAKE_FLAGS}
    - make -j2
    - make test CTEST_OUTPUT_ON_FAILURE=TRUE
    - if [[ ${CPP_CHECK} ]]; then cppcheck ../src/; fi

